# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-cov
        pip install coverage        
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: install elastix
      run: |
        wget -P ~/ElastixDownload "https://github.com/SuperElastix/elastix/releases/download/5.0.1/elastix-5.0.1-linux.tar.bz2"
    - name: Test with pytest
      run: |
        mkdir /home/runner/elastix
        tar -xvjf /home/runner/ElastixDownload/elastix-5.0.1-linux.tar.bz2 -C /home/runner/elastix        
        PATH=$PATH:~/elastix/elastix-5.0.1-linux/bin
        LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/elastix/elastix-5.0.1-linux/lib
        echo "$PATH"
        echo "$LD_LIBRARY_PATH"      
        pytest --cov=CBCTCardiacSegmentation/ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
